matrix:
  include:
    - before_install:
        - sudo apt-get install check 
      language: c
      compiler: gcc
      script:
        - cd C-Code/
        - make 

    - sudo: required
      install:
        - apt-get update -y
        - apt-get install -y python-pip python-dev
        - cd Flask_Dockerized/flask_webapp
        - pip install -r requirements.txt
      script:
        - cd Flask_Dockerized/flask_webapp
        - pytest

    - language: generic            
      sudo: required
      services:
        - docker
      before_install:
        - cd Flask_Dockerized/
        - docker-compose pull
        - docker-compose build
      install:
        - docker-compose up -d
      script:
        - docker-compose down

      
notifications:
  email:
    - ys3334@nyu.edu