version: '3.1'
services:
 node-app:
  restart: always
  user: root
  build: .
  image: ys3334/spell_check:2.0
  ports:
   - "8080:5000"
  secrets:
   - secretfile

secrets:
 secretfile:
  file: secretfile.yml
