apiVersion: v1
kind: Pod
metadata:
  name: spellcheckpod
  labels:
    app: spellchecker
spec:
  containers:
  - name: spellchecker
    image: ys3334/spell_check
    ports:
      - containerPort: 5000
    volumeMounts:
    - name: secretfile
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secretfile
    secret:
      secretName: secretfile